//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIstekler
    {
        public int ID { get; set; }
        public Nullable<int> APID { get; set; }
        public Nullable<int> BPID { get; set; }
        public Nullable<int> OGRENCIID { get; set; }
        public Nullable<int> APONAY { get; set; }
        public Nullable<int> BPONAY { get; set; }
        public string APACIKLAMA { get; set; }
        public string BPACIKLAMA { get; set; }
        public string APCEVAP { get; set; }
        public string BPCEVAP { get; set; }
    
        public virtual TBLOgrenciler TBLOgrenciler { get; set; }
        public virtual TBLOgretmenler TBLOgretmenler { get; set; }
        public virtual TBLOgretmenler TBLOgretmenler1 { get; set; }
    }
}
