//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKonular
    {
        public int ID { get; set; }
        public Nullable<int> OGRETMENID { get; set; }
        public string KONU { get; set; }
        public string ICERIK { get; set; }
    
        public virtual TBLOgretmenler TBLOgretmenler { get; set; }
    }
}
