//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOgretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOgretmenler()
        {
            this.TBLKonular = new HashSet<TBLKonular>();
            this.TBLIstekler = new HashSet<TBLIstekler>();
            this.TBLIstekler1 = new HashSet<TBLIstekler>();
            this.TBLDuyurular = new HashSet<TBLDuyurular>();
            this.TBLMesajlar = new HashSet<TBLMesajlar>();
        }
    
        public int ID { get; set; }
        public string ISIM { get; set; }
        public string MAIL { get; set; }
        public string SIFRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKonular> TBLKonular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIstekler> TBLIstekler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIstekler> TBLIstekler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDuyurular> TBLDuyurular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMesajlar> TBLMesajlar { get; set; }
    }
}
