//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOgrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOgrenciler()
        {
            this.TBLIstekler = new HashSet<TBLIstekler>();
            this.TBLMesajlar = new HashSet<TBLMesajlar>();
        }
    
        public int ID { get; set; }
        public string ISIM { get; set; }
        public string MAIL { get; set; }
        public string SIFRE { get; set; }
        public string TELEFON { get; set; }
        public string BOLUM { get; set; }
        public string ADRES { get; set; }
        public Nullable<int> NUMARA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIstekler> TBLIstekler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMesajlar> TBLMesajlar { get; set; }
    }
}
